// export { default as DoppioCheddarImage } from "./old_hamburger/DoppioCheddar.png";
// export { default as HotBurgImage } from "./old_hamburger/HotBurg.png";
// export { default as PolloImage } from "./old_hamburger/Pollo.png";
// export { default as VegetarianoImage } from "./old_hamburger/Vegetariano.png";
// export { default as MonteboreBurgImage } from "./old_hamburger/MonteboreBurg.png";
// export { default as PiggyBurgImage } from "./old_hamburger/PiggyBurg.png";
// export { default as UovoBurgImage } from "./old_hamburger/UovoBurg.png";
// export { default as RibsBurgImage } from "./old_hamburger/RibsBurg.png";
// export { default as HotDogClassicImage } from "./old_hamburger/HotDogClassic.png";
// export { default as HotDogGourmetImage } from "./old_hamburger/HotDogGourmet.png";
export { default as DoppioCheddarImage } from "./new_hamburger/DoppioCheddar.png";
export { default as HotBurgImage } from "./new_hamburger/HotBurg.png";
export { default as PolloImage } from "./new_hamburger/Pollo.png";
export { default as VegetarianoImage } from "./new_hamburger/Vegetariano.png";
export { default as MonteboreBurgImage } from "./new_hamburger/MonteboreBurg.png";
export { default as PiggyBurgImage } from "./new_hamburger/PiggyBurg.png";
export { default as UovoBurgImage } from "./new_hamburger/UovoBurg.png";
export { default as HotDogClassicImage } from "./new_hamburger/HotDogClassic.png";

export { default as Photo1 } from "./carousel/photo1.png";
export { default as Photo2 } from "./carousel/photo2.png";
export { default as Photo3 } from "./carousel/photo3.png";
export { default as Photo3_bis } from "./carousel/photo3_bis.png";
export { default as Photo4 } from "./carousel/photo4.png";
export { default as Photo5 } from "./carousel/photo5.png";
export { default as Photo6 } from "./carousel/photo6.png";
export { default as Photo7 } from "./carousel/photo7.png";
export { default as Photo8 } from "./carousel/photo8.png";
export { default as Photo9 } from "./carousel/photo9.png";
export { default as Photo10 } from "./carousel/photo10.png";
export { default as Photo11 } from "./carousel/photo11.png";
export { default as Photo12 } from "./carousel/photo12.png";
export { default as Photo13 } from "./carousel/photo13.png";

export { default as SfondoCantina } from "./background/SfondoCantina.png";
export { default as SfondoDessert } from "./background/SfondoDessert.png";
export { default as SfondoDrink } from "./background/SfondoDrink.png";
export { default as SfondoHamburger } from "./background/SfondoHamburger.png";
export { default as SfondoMenu } from "./background/SfondoMenu.png";

export { default as CheesecakeMandorleImage } from "./menu/CheesecakeMandorle.png";
export { default as CheesecakePistacchioImage } from "./menu/CheesecakePistacchio.png";
export { default as CheesecakeGianduiaLamponiImage } from "./menu/CheesecakeGianduiaLamponi.png";
export { default as CheesecakeLimoneImage } from "./menu/CheesecakeLimone.png";
export { default as BunetImage } from "./menu/Bunet.png";
export { default as MeringaImage } from "./menu/Meringa.png";
export { default as GelatoFragoleImage } from "./menu/GelatoFragole.png";
export { default as TiramisuImage } from "./menu/Tiramisu.png";
export { default as BavareseCaffeImage } from "./menu/BavareseCaffe.png";
export { default as BavareseCiliegieImage } from "./menu/BavareseCiliegie.png";
export { default as CrostataFruttaImage } from "./menu/CrostataDiFrutta.png";
export { default as SfogliataImage } from "./menu/Sfogliata.png";
export { default as ZuppaIngleseImage } from "./menu/ZuppaInglese.png";
export { default as TortaMeleImage } from "./menu/TortaMele.png";
export { default as ZuccottoImage } from "./menu/Zuccotto.png";
